### ISSUE TITLE
Problems running the example overview

### ISSUE THREAD

**Issue by AlexManoJAM** [espressif/esp32c3-direct-boot-example#3]
Hi, I'm a student doing a dissertation with esp32c3 and I was trying not to use the esp-IDF framework and its dependencies. Therefore the direct boot fracture is actually what I wanted but trying to follow the example on a windows system, instead of getting the expected output I get this:
![image](https://user-images.githubusercontent.com/35406517/142415340-75946c7e-88e9-47c2-a232-26edc48053db.png)

I was hoping you can help with this.
 p.s I'm quite new with CMake and toolchains

**Comment by igrr** [comment]
It looks like CMake toolchain file didn't get set for some reason, and CMake is trying to use the host compiler instead of the cross-compiler.

Could you try deleting the build directory, creating it again, and running CMake again?
```
cmake ..
```
Then check the output. If CMake hasn't detected the RISC-V compiler, it might be that you don't have it in the PATH.

If you get stuck, please post the output you get from CMake.

Once that part is resolved, you can proceed to running `cmake --build .`

**Comment by AlexManoJAM** [comment]
This is the  output I get running CMake again:
![image](https://user-images.githubusercontent.com/35406517/142443181-5a6f0850-91d0-4e62-a20c-4499a31d4692.png)
I think I got the right PATH to the RISC-V compiler but running 'cmake --build .' keeps getting errors
![image](https://user-images.githubusercontent.com/35406517/142444721-1167854c-e7c7-4b26-89aa-0645cbf39006.png)

**Comment by igrr** [comment]
It seems to find the assembler from the RISC-V toolchain, but not the C and C++ compilers — instead it finds cl.exe from MSVC. Perhaps this is because CMake comes from MSVC installation? I don't have a windows computer with MSVC installed, so it's a bit hard to help you troubleshoot this, unfortunately.
